*Generated by GrADS Color Maker
*所有变量需使用小写 其余字符大小写均可
* $r $g $b 18 $id 为可用变量

*18 表示输出多少个 默认全部输出 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 表示用空格分隔的id列表



 'set rgb 20 36 0 216'
 'set rgb 21 24 28 247'
 'set rgb 22 40 87 255'
 'set rgb 23 61 135 255'
 'set rgb 24 86 176 255'
 'set rgb 25 117 211 255'
 'set rgb 26 153 234 255'
 'set rgb 27 188 249 255'
 'set rgb 28 234 255 255'
 'set rgb 29 255 255 234'
 'set rgb 30 255 241 188'
 'set rgb 31 255 214 153'
 'set rgb 32 255 172 117'
 'set rgb 33 255 120 86'
 'set rgb 34 255 61 61'
 'set rgb 35 247 39 53'
 'set rgb 36 216 21 47'
 'set rgb 37 165 0 33'

'set rbcols 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 '
return
